baseurl: https://UW-POLS501.github.io/2018/
ignoreFiles: [\.Rmd$, \.Rmarkdown$, _files$, _cache$]
languageCode: en-US
buildFuture: true
blackfriday:
  # otherwise DOI forward slashes become fractions
  fractions: false
menu:
  main:
  - {name: Syllabus, url: "/"}
  - {name: Schedule, url: /schedule/}
  - {name: Assignments, url: /assignments/}
  - {name: Pages, url: /pages/}
params:
  useBootstrap: true
  highlightjsCDN: '//cdn.bootcss.com'
  highlightjsLang: [r, yaml, bash]
  highlightjsTheme: github
  highlightjsVersion: 9.11.0
  MathJaxCDN: '//cdn.bootcss.com'
  MathJaxVersion: 2.7.1
  NavbarBrand:
    URL: "/"
    name: "POLS 503"
  meetings:
    - room:
        building: Savery
        number: '139'
        url: 'https://www.washington.edu/maps/#!/sav'
      startTime: '2018-03-26T16:30:00-08:00'
      endTime: '2018-03-26T17:50:00-07:00'
      lab: false
    - room:
        building: Savery
        number: '139'
        url: 'https://www.washington.edu/maps/#!/sav'
      startTime: '2018-03-28T16:30:00-07:00'
      endTime: '2018-03-28T17:50:00-07:00'
      lab: false
    - room:
        building: Savery
        number: '121'
        url: "https://www.washington.edu/maps/#!/sav"
      startTime: '2018-03-30T13:30:00-07:00'
      endTime: '2018-03-30T15:20:00-07:00'
      lab: true
  course:
    institution: 'University of Washington'
    mailing_lists: [pols503a_sp18@uw.edu, csss503a_sp18@uw.edu]
    number: "POLS/CS&SS 503"
    term: Spring
    title: "Advanced Quantitative Political Methodology"
    year: '2018'
  description: >
    The website for University of Washington: POLS 503
    "Advanced Quantitative Political Methodology" (Spring 2018)
  inprogress: false
  instructor:
    email: 'jrnold@uw.edu'
    name: 'Jeffrey B. Arnold'
    officeHours:
      room: "Smith 221B"
      buildingURL: "https://www.washington.edu/maps/#!/smi"
      time: 'Th 12&ndash;1 pm, 4&ndash;5 pm'
    title: 'Assistant Professor, Political Science; Core Faculty, CSSS'
    url: 'https://jrnold.com'

  license:
    URL: 'http://creativecommons.org/licenses/by/4.0/'
    name: 'Creative Commons Attribution 4.0 International License'
  sourceUrl: "https://github.com/UW-POLS501/2018/"
  ta:
    email: 'chgarner@uw.edu'
    name: 'Calvin Garner'
    officeHours:
      room: Gowen 30
      time: 'W 12&ndash;2 pm'
      buildingURL: "https://www.washington.edu/maps/#!/gow"
    title: 'Graduate Student, Political Science'
    url: 'https://www.polisci.washington.edu/people/calvin-garner'
permalinks:
  page: '/:slug/'
  post: '/:year/:month/:day/:slug/'
publishDir: docs
theme: local
title: 'POLS 503: Advanced Quantitative Political Methodology'
