---
title: Onboarding for POLS 503
---

Please complete the following before Wednesday, March 28, 2018.

1.  Sign up for our Slack workplace, <https://uwpolsmethods.slack.com/>. We will use this for announcements, and asking and answering questions in this course. You should have received an invite. If not email the [instructor](jrnold@uw.edu) to receive one.

2.  Tell us about yourself: Complete the pre-course survey. If you are registered for the course, you should have received an email. If not, you can find a link pinned on the `#announcements` channel of Slack.

2.  We will use [git](https://git-scm.com/) for version control and [GitHub](https://github.com/) for distributing, collecting, and commenting on assignments. 

    1.  Download [Git](https://git-scm.com/downloads) and install git.
        You should be able to use defaults for all settings.
    2.  Sign up for a GitHub account at <https://github.com> (if you do no already have one).
    3.  Tell us what your GitHub username is using the form emailed to you,
        or that can be found pinned on the `#onboarding` channel in Slack.
        
4.  Download and install the latest version of R.

    1.  If you have R installed already, check that you have the latest version of R. 
        As of the start of this course (March 26, 2018), the most recent version of R is **3.4.4**. 
        You can find this in R:
        
        ```rconsole
        $ sessionInf()
        ```
        
    2.  If you do not have R or the latest version of it installed, then download it from [CRAN](https://cloud.r-project.org/).

5.  (Recommended) Download that install RStudio Desktop (Open Source Edition). RStudio is an [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment) that provides a user-friendly interface to R.
    If you are proficient with R and have been using another IDE or text editor with R, you can skip this step.

    1.  If you do not have RStudio installed, download and install it from [here](https://www.rstudio.com/products/rstudio/download/#download).
    
    2.  If you already have RStudio installed, check that you have the latest version
        by selecting `Help > Check for Updates` in the menu. Download and install
        the newest version if not.

6.  (Recommended) Download and install LaTeX if you don't have it installed.
    You will not need to use LaTeX directly (though I encourage you to use it for academic writing), 
    but it is needed to create PDFs from R Markdown.
    There are multiple LaTeX distributions; install the appropriate one for your operating system.

    1.  On MacOS, install [MacTeX](http://www.tug.org/mactex/).
    2.  On Windows, install [MikTeX](https://miktex.org/howto/install-miktex).
    3.  On Linux, `tex-live` is a common LaTeX distribution.
